spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USER:admin}
      password: ${MONGO_PASSWORD:admin}
      port: 27017
      database: project-base
      authentication-database: admin
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 8080

springdoc:
  show-actuator: true